export const Fonts = [
    'Caveat',
    'Comfortaa',
    'Lobster Two',
    'Lobster',
    'Lora',
    'Montserrat',
    'Montserrat Alternates',
    'Montserrat Subrayada',
    'Nunito Sans',
    'Nunito',
    'Open Sans',
    'Open Sans Condensed',
    'Roboto',
    'Roboto Condensed',
    'Roboto Mono',
    'Roboto Slab',
    'Spectral',
    'Syncopate',
    'Ubuntu',
    'Ubuntu Condensed',
    'Ubuntu Mono',
    'Dancing Script',
];
