import { Country, CountryEmergencyNumber } from '../../app/models';

export const countries: Country[] = [
    { name: 'Afghanistan', code: 'AF', vatPrefix: null },
    { name: 'Åland Islands', code: 'AX', vatPrefix: null },
    { name: 'Albania', code: 'AL', vatPrefix: null },
    { name: 'Algeria', code: 'DZ', vatPrefix: null },
    { name: 'American Samoa', code: 'AS', vatPrefix: null },
    { name: 'Andorra', code: 'AD', vatPrefix: null },
    { name: 'Angola', code: 'AO', vatPrefix: null },
    { name: 'Anguilla', code: 'AI', vatPrefix: null },
    { name: 'Antarctica', code: 'AQ', vatPrefix: null },
    { name: 'Antigua and Barbuda', code: 'AG', vatPrefix: null },
    { name: 'Argentina', code: 'AR', vatPrefix: null },
    { name: 'Armenia', code: 'AM', vatPrefix: null },
    { name: 'Aruba', code: 'AW', vatPrefix: null },
    { name: 'Australia', code: 'AU', vatPrefix: null },
    { name: 'Austria', code: 'AT', vatPrefix: 'AT' },
    { name: 'Azerbaijan', code: 'AZ', vatPrefix: null },
    { name: 'Bahamas', code: 'BS', vatPrefix: null },
    { name: 'Bahrain', code: 'BH', vatPrefix: null },
    { name: 'Bangladesh', code: 'BD', vatPrefix: null },
    { name: 'Barbados', code: 'BB', vatPrefix: null },
    { name: 'Belarus', code: 'BY', vatPrefix: null },
    { name: 'Belgium', code: 'BE', vatPrefix: 'BE' },
    { name: 'Belize', code: 'BZ', vatPrefix: null },
    { name: 'Benin', code: 'BJ', vatPrefix: null },
    { name: 'Bermuda', code: 'BM', vatPrefix: null },
    { name: 'Bhutan', code: 'BT', vatPrefix: null },
    { name: 'Bolivia', code: 'BO', vatPrefix: null },
    { name: 'Bosnia and Herzegovina', code: 'BA', vatPrefix: null },
    { name: 'Botswana', code: 'BW', vatPrefix: null },
    { name: 'Bouvet Island', code: 'BV', vatPrefix: null },
    { name: 'Brazil', code: 'BR', vatPrefix: null },
    { name: 'British Indian Ocean Territory', code: 'IO', vatPrefix: null },
    { name: 'Brunei Darussalam', code: 'BN', vatPrefix: null },
    { name: 'Bulgaria', code: 'BG', vatPrefix: 'BG' },
    { name: 'Burkina Faso', code: 'BF', vatPrefix: null },
    { name: 'Burundi', code: 'BI', vatPrefix: null },
    { name: 'Cambodia', code: 'KH', vatPrefix: null },
    { name: 'Cameroon', code: 'CM', vatPrefix: null },
    { name: 'Canada', code: 'CA', vatPrefix: null },
    { name: 'Cape Verde', code: 'CV', vatPrefix: null },
    { name: 'Cayman Islands', code: 'KY', vatPrefix: null },
    { name: 'Central African Republic', code: 'CF', vatPrefix: null },
    { name: 'Chad', code: 'TD', vatPrefix: null },
    { name: 'Chile', code: 'CL', vatPrefix: null },
    { name: 'China', code: 'CN', vatPrefix: null },
    { name: 'Christmas Island', code: 'CX', vatPrefix: null },
    { name: 'Cocos (Keeling) Islands', code: 'CC', vatPrefix: null },
    { name: 'Colombia', code: 'CO', vatPrefix: null },
    { name: 'Comoros', code: 'KM', vatPrefix: null },
    { name: 'Congo', code: 'CG', vatPrefix: null },
    { name: 'Congo, The Democratic Republic of the', code: 'CD', vatPrefix: null },
    { name: 'Cook Islands', code: 'CK', vatPrefix: null },
    { name: 'Costa Rica', code: 'CR', vatPrefix: null },
    { name: 'Cote D\'Ivoire', code: 'CI', vatPrefix: null },
    { name: 'Croatia', code: 'HR', vatPrefix: 'HR' },
    { name: 'Cuba', code: 'CU', vatPrefix: null },
    { name: 'Cyprus', code: 'CY', vatPrefix: 'CY' },
    { name: 'Czech Republic', code: 'CZ', vatPrefix: 'CZ' },
    { name: 'Denmark', code: 'DK', vatPrefix: 'DK' },
    { name: 'Djibouti', code: 'DJ', vatPrefix: null },
    { name: 'Dominica', code: 'DM', vatPrefix: null },
    { name: 'Dominican Republic', code: 'DO', vatPrefix: null },
    { name: 'Ecuador', code: 'EC', vatPrefix: null },
    { name: 'Egypt', code: 'EG', vatPrefix: null },
    { name: 'El Salvador', code: 'SV', vatPrefix: null },
    { name: 'Equatorial Guinea', code: 'GQ', vatPrefix: null },
    { name: 'Eritrea', code: 'ER', vatPrefix: null },
    { name: 'Estonia', code: 'EE', vatPrefix: 'EE' },
    { name: 'Ethiopia', code: 'ET', vatPrefix: null },
    { name: 'Falkland Islands (Malvinas)', code: 'FK', vatPrefix: null },
    { name: 'Faroe Islands', code: 'FO', vatPrefix: null },
    { name: 'Fiji', code: 'FJ', vatPrefix: null },
    { name: 'Finland', code: 'FI', vatPrefix: 'FI' },
    { name: 'France', code: 'FR', vatPrefix: 'FR' },
    { name: 'French Guiana', code: 'GF', vatPrefix: null },
    { name: 'French Polynesia', code: 'PF', vatPrefix: null },
    { name: 'French Southern Territories', code: 'TF', vatPrefix: null },
    { name: 'Gabon', code: 'GA', vatPrefix: null },
    { name: 'Gambia', code: 'GM', vatPrefix: null },
    { name: 'Georgia', code: 'GE', vatPrefix: null },
    { name: 'Germany', code: 'DE', vatPrefix: 'DE' },
    { name: 'Ghana', code: 'GH', vatPrefix: null },
    { name: 'Gibraltar', code: 'GI', vatPrefix: null },
    { name: 'Greece', code: 'GR', vatPrefix: 'EL' },
    { name: 'Greenland', code: 'GL', vatPrefix: null },
    { name: 'Grenada', code: 'GD', vatPrefix: null },
    { name: 'Guadeloupe', code: 'GP', vatPrefix: null },
    { name: 'Guam', code: 'GU', vatPrefix: null },
    { name: 'Guatemala', code: 'GT', vatPrefix: null },
    { name: 'Guernsey', code: 'GG', vatPrefix: null },
    { name: 'Guinea', code: 'GN', vatPrefix: null },
    { name: 'Guinea-Bissau', code: 'GW', vatPrefix: null },
    { name: 'Guyana', code: 'GY', vatPrefix: null },
    { name: 'Haiti', code: 'HT', vatPrefix: null },
    { name: 'Heard Island and Mcdonald Islands', code: 'HM', vatPrefix: null },
    { name: 'Holy See (Vatican City State)', code: 'VA', vatPrefix: null },
    { name: 'Honduras', code: 'HN', vatPrefix: null },
    { name: 'Hong Kong', code: 'HK', vatPrefix: null },
    { name: 'Hungary', code: 'HU', vatPrefix: 'HU' },
    { name: 'Iceland', code: 'IS', vatPrefix: null },
    { name: 'India', code: 'IN', vatPrefix: null },
    { name: 'Indonesia', code: 'ID', vatPrefix: null },
    { name: 'Iran, Islamic Republic Of', code: 'IR', vatPrefix: null },
    { name: 'Iraq', code: 'IQ', vatPrefix: null },
    { name: 'Ireland', code: 'IE', vatPrefix: 'IE' },
    { name: 'Isle of Man', code: 'IM', vatPrefix: null },
    { name: 'Israel', code: 'IL', vatPrefix: null },
    { name: 'Italy', code: 'IT', vatPrefix: 'IT' },
    { name: 'Jamaica', code: 'JM', vatPrefix: null },
    { name: 'Japan', code: 'JP', vatPrefix: null },
    { name: 'Jersey', code: 'JE', vatPrefix: null },
    { name: 'Jordan', code: 'JO', vatPrefix: null },
    { name: 'Kazakhstan', code: 'KZ', vatPrefix: null },
    { name: 'Kenya', code: 'KE', vatPrefix: null },
    { name: 'Kiribati', code: 'KI', vatPrefix: null },
    { name: 'Korea, Democratic People\'S Republic of', code: 'KP', vatPrefix: null },
    { name: 'Korea, Republic of', code: 'KR', vatPrefix: null },
    { name: 'Kuwait', code: 'KW', vatPrefix: null },
    { name: 'Kyrgyzstan', code: 'KG', vatPrefix: null },
    { name: 'Lao People\'S Democratic Republic', code: 'LA', vatPrefix: null },
    { name: 'Latvia', code: 'LV', vatPrefix: 'LV' },
    { name: 'Lebanon', code: 'LB', vatPrefix: null },
    { name: 'Lesotho', code: 'LS', vatPrefix: null },
    { name: 'Liberia', code: 'LR', vatPrefix: null },
    { name: 'Libyan Arab Jamahiriya', code: 'LY', vatPrefix: null },
    { name: 'Liechtenstein', code: 'LI', vatPrefix: null },
    { name: 'Lithuania', code: 'LT', vatPrefix: 'LT' },
    { name: 'Luxembourg', code: 'LU', vatPrefix: 'LU' },
    { name: 'Macao', code: 'MO', vatPrefix: null },
    { name: 'Madagascar', code: 'MG', vatPrefix: null },
    { name: 'Malawi', code: 'MW', vatPrefix: null },
    { name: 'Malaysia', code: 'MY', vatPrefix: null },
    { name: 'Maldives', code: 'MV', vatPrefix: null },
    { name: 'Mali', code: 'ML', vatPrefix: null },
    { name: 'Malta', code: 'MT', vatPrefix: 'MT' },
    { name: 'Marshall Islands', code: 'MH', vatPrefix: null },
    { name: 'Martinique', code: 'MQ', vatPrefix: null },
    { name: 'Mauritania', code: 'MR', vatPrefix: null },
    { name: 'Mauritius', code: 'MU', vatPrefix: null },
    { name: 'Mayotte', code: 'YT', vatPrefix: null },
    { name: 'Mexico', code: 'MX', vatPrefix: null },
    { name: 'Micronesia, Federated States of', code: 'FM', vatPrefix: null },
    { name: 'Moldova, Republic of', code: 'MD', vatPrefix: null },
    { name: 'Monaco', code: 'MC', vatPrefix: null },
    { name: 'Mongolia', code: 'MN', vatPrefix: null },
    { name: 'Montenegro', code: 'ME', vatPrefix: null },
    { name: 'Montserrat', code: 'MS', vatPrefix: null },
    { name: 'Morocco', code: 'MA', vatPrefix: null },
    { name: 'Mozambique', code: 'MZ', vatPrefix: null },
    { name: 'Myanmar', code: 'MM', vatPrefix: null },
    { name: 'Namibia', code: 'NA', vatPrefix: null },
    { name: 'Nauru', code: 'NR', vatPrefix: null },
    { name: 'Nepal', code: 'NP', vatPrefix: null },
    { name: 'Netherlands', code: 'NL', vatPrefix: 'NL' },
    { name: 'Netherlands Antilles', code: 'AN', vatPrefix: null },
    { name: 'New Caledonia', code: 'NC', vatPrefix: null },
    { name: 'New Zealand', code: 'NZ', vatPrefix: null },
    { name: 'Nicaragua', code: 'NI', vatPrefix: null },
    { name: 'Niger', code: 'NE', vatPrefix: null },
    { name: 'Nigeria', code: 'NG', vatPrefix: null },
    { name: 'Niue', code: 'NU', vatPrefix: null },
    { name: 'Norfolk Island', code: 'NF', vatPrefix: null },
    { name: 'North Macedonia', code: 'MK', vatPrefix: null },
    { name: 'Northern Mariana Islands', code: 'MP', vatPrefix: null },
    { name: 'Norway', code: 'NO', vatPrefix: null },
    { name: 'Oman', code: 'OM', vatPrefix: null },
    { name: 'Pakistan', code: 'PK', vatPrefix: null },
    { name: 'Palau', code: 'PW', vatPrefix: null },
    { name: 'Palestinian Territory, Occupied', code: 'PS', vatPrefix: null },
    { name: 'Panama', code: 'PA', vatPrefix: null },
    { name: 'Papua New Guinea', code: 'PG', vatPrefix: null },
    { name: 'Paraguay', code: 'PY', vatPrefix: null },
    { name: 'Peru', code: 'PE', vatPrefix: null },
    { name: 'Philippines', code: 'PH', vatPrefix: null },
    { name: 'Pitcairn', code: 'PN', vatPrefix: null },
    { name: 'Poland', code: 'PL', vatPrefix: 'PL' },
    { name: 'Portugal', code: 'PT', vatPrefix: 'PT' },
    { name: 'Puerto Rico', code: 'PR', vatPrefix: null },
    { name: 'Qatar', code: 'QA', vatPrefix: null },
    { name: 'Reunion', code: 'RE', vatPrefix: null },
    { name: 'Romania', code: 'RO', vatPrefix: 'RO' },
    { name: 'Russian Federation', code: 'RU', vatPrefix: null },
    { name: 'Rwanda', code: 'RW', vatPrefix: null },
    { name: 'Saint Helena', code: 'SH', vatPrefix: null },
    { name: 'Saint Kitts and Nevis', code: 'KN', vatPrefix: null },
    { name: 'Saint Lucia', code: 'LC', vatPrefix: null },
    { name: 'Saint Pierre and Miquelon', code: 'PM', vatPrefix: null },
    { name: 'Saint Vincent and the Grenadines', code: 'VC', vatPrefix: null },
    { name: 'Samoa', code: 'WS', vatPrefix: null },
    { name: 'San Marino', code: 'SM', vatPrefix: null },
    { name: 'Sao Tome and Principe', code: 'ST', vatPrefix: null },
    { name: 'Saudi Arabia', code: 'SA', vatPrefix: null },
    { name: 'Senegal', code: 'SN', vatPrefix: null },
    { name: 'Serbia', code: 'RS', vatPrefix: null },
    { name: 'Seychelles', code: 'SC', vatPrefix: null },
    { name: 'Sierra Leone', code: 'SL', vatPrefix: null },
    { name: 'Singapore', code: 'SG', vatPrefix: null },
    { name: 'Slovakia', code: 'SK', vatPrefix: 'SK' },
    { name: 'Slovenia', code: 'SI', vatPrefix: 'SI' },
    { name: 'Solomon Islands', code: 'SB', vatPrefix: null },
    { name: 'Somalia', code: 'SO', vatPrefix: null },
    { name: 'South Africa', code: 'ZA', vatPrefix: null },
    { name: 'South Georgia and the South Sandwich Islands', code: 'GS', vatPrefix: null },
    { name: 'Spain', code: 'ES', vatPrefix: 'ES' },
    { name: 'Sri Lanka', code: 'LK', vatPrefix: null },
    { name: 'Sudan', code: 'SD', vatPrefix: null },
    { name: 'Suriname', code: 'SR', vatPrefix: null },
    { name: 'Svalbard and Jan Mayen', code: 'SJ', vatPrefix: null },
    { name: 'Swaziland', code: 'SZ', vatPrefix: null },
    { name: 'Sweden', code: 'SE', vatPrefix: 'SE' },
    { name: 'Switzerland', code: 'CH', vatPrefix: null },
    { name: 'Syrian Arab Republic', code: 'SY', vatPrefix: null },
    { name: 'Taiwan, Province of China', code: 'TW', vatPrefix: null },
    { name: 'Tajikistan', code: 'TJ', vatPrefix: null },
    { name: 'Tanzania, United Republic of', code: 'TZ', vatPrefix: null },
    { name: 'Thailand', code: 'TH', vatPrefix: null },
    { name: 'Timor-Leste', code: 'TL', vatPrefix: null },
    { name: 'Togo', code: 'TG', vatPrefix: null },
    { name: 'Tokelau', code: 'TK', vatPrefix: null },
    { name: 'Tonga', code: 'TO', vatPrefix: null },
    { name: 'Trinidad and Tobago', code: 'TT', vatPrefix: null },
    { name: 'Tunisia', code: 'TN', vatPrefix: null },
    { name: 'Turkey', code: 'TR', vatPrefix: null },
    { name: 'Turkmenistan', code: 'TM', vatPrefix: null },
    { name: 'Turks and Caicos Islands', code: 'TC', vatPrefix: null },
    { name: 'Tuvalu', code: 'TV', vatPrefix: null },
    { name: 'Uganda', code: 'UG', vatPrefix: null },
    { name: 'Ukraine', code: 'UA', vatPrefix: null },
    { name: 'United Arab Emirates', code: 'AE', vatPrefix: null },
    { name: 'United Kingdom', code: 'GB', vatPrefix: 'GB' },
    { name: 'United States', code: 'US', vatPrefix: null },
    { name: 'United States Minor Outlying Islands', code: 'UM', vatPrefix: null },
    { name: 'Uruguay', code: 'UY', vatPrefix: null },
    { name: 'Uzbekistan', code: 'UZ', vatPrefix: null },
    { name: 'Vanuatu', code: 'VU', vatPrefix: null },
    { name: 'Venezuela', code: 'VE', vatPrefix: null },
    { name: 'Viet Nam', code: 'VN', vatPrefix: null },
    { name: 'Virgin Islands, U.S.', code: 'VI', vatPrefix: null },
    { name: 'Wallis and Futuna', code: 'WF', vatPrefix: null },
    { name: 'Western Sahara', code: 'EH', vatPrefix: null },
    { name: 'Yemen', code: 'YE', vatPrefix: null },
    { name: 'Zambia', code: 'ZM', vatPrefix: null },
    { name: 'Zimbabwe', code: 'ZW', vatPrefix: null }

];



export const country_codes_eu: string[] = [
    'AT',
    'BE',
    'HR',
    'CY',
    'EE',
    'FI',
    'FR',
    'DE',
    'GR',
    'IE',
    'IT',
    'LV',
    'LT',
    'LU',
    'MT',
    'NL',
    'PT',
    'SK',
    'SI',
    'ES',
];



// https://www.adducation.info/general-knowledge-travel-and-transport/emergency-numbers/
export const countries_emergency_numbers: CountryEmergencyNumber[] = [
    {
        country_code: 'AF',
        country_name: 'Afghanistan',
        country_icon: '🇦🇫',
        emergency: 'null',
        police: '119',
        ambulance: '119, 102',
        fire: '112, 119',
        group: 'Asia',
        calling_codes: '93',
    },
    {
        country_code: 'AL',
        country_name: 'Albania',
        country_icon: '🇦🇱',
        emergency: 'null',
        police: '129',
        ambulance: '127',
        fire: '128',
        group: 'Europe',
        calling_codes: '355',
    },
    {
        country_code: 'DZ',
        country_name: 'Algeria',
        country_icon: '🇩🇿',
        emergency: 'null',
        police: '17',
        ambulance: '14',
        fire: '14',
        group: 'Africa',
        calling_codes: '213',
    },
    {
        country_code: 'AS',
        country_name: 'American Samoa',
        country_icon: '🇦🇸',
        emergency: '911',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'Oceania',
        calling_codes: '+1 684',
    },
    {
        country_code: 'AD',
        country_name: 'Andorra',
        country_icon: '🇦🇩',
        emergency: '112',
        police: '110',
        ambulance: '118',
        fire: '118',
        group: 'Europe',
        calling_codes: '376',
    },
    {
        country_code: 'AO',
        country_name: 'Angola',
        country_icon: '🇦🇴',
        emergency: 'null',
        police: '113',
        ambulance: '112 or 116',
        fire: '115',
        group: 'Africa',
        calling_codes: '244',
    },
    {
        country_code: 'AI',
        country_name: 'Anguilla',
        country_icon: '🇦🇮',
        emergency: '911',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'British, Caribbean',
        calling_codes: '+1 264',
    },
    {
        country_code: 'AG',
        country_name: 'Antigua and Barbuda',
        country_icon: '🇦🇬',
        emergency: '911 or 999 or 777',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'Caribbean, North America',
        calling_codes: '+1 268',
    },
    {
        country_code: 'AR',
        country_name: 'Argentina',
        country_icon: '🇦🇷',
        emergency: '911',
        police: '101',
        ambulance: '107',
        fire: '100',
        group: 'South America',
        calling_codes: '54',
    },
    {
        country_code: 'AM',
        country_name: 'Armenia',
        country_icon: '🇦🇲',
        emergency: '911 or 112',
        police: '102',
        ambulance: '103',
        fire: '101',
        group: 'Europe, Asia',
        calling_codes: '374',
    },
    {
        country_code: 'AW',
        country_name: 'Aruba',
        country_icon: '🇦🇼',
        emergency: '911',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'Caribbean, North America',
        calling_codes: '297',
    },
    {
        country_code: 'null',
        country_name: 'Ascension Island',
        country_icon: '🇸🇭',
        emergency: '999',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'South Atlantic Ocean',
        calling_codes: '247',
    },
    {
        country_code: 'AU',
        country_name: 'Australia',
        country_icon: '🇦🇺',
        emergency: 'null',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'Australia, Oceania',
        calling_codes: '61',
    },
    {
        country_code: 'AT',
        country_name: 'Austria',
        country_icon: '🇦🇹',
        emergency: '112',
        police: '112, 133',
        ambulance: '144',
        fire: '122',
        group: 'EU, Europe',
        calling_codes: '43',
    },
    {
        country_code: 'AZ',
        country_name: 'Azerbaijan',
        country_icon: '🇦🇿',
        emergency: 'null',
        police: '102',
        ambulance: '103',
        fire: '101',
        group: 'Asia, Europe',
        calling_codes: '94',
    },
    {
        country_code: 'BS',
        country_name: 'Bahamas',
        country_icon: '🇧🇸',
        emergency: '911 or 919 112 mobiles',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'Caribbean, North America',
        calling_codes: '+1 242',
    },
    {
        country_code: 'BH',
        country_name: 'Bahrain',
        country_icon: '🇧🇭',
        emergency: '999 or 112 mobiles',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'Asia',
        calling_codes: '973',
    },
    {
        country_code: 'BD',
        country_name: 'Bangladesh',
        country_icon: '🇧🇩',
        emergency: '999',
        police: '999',
        ambulance: '999',
        fire: '999',
        group: 'Asia',
        calling_codes: '880',
    },
    {
        country_code: 'BB',
        country_name: 'Barbados',
        country_icon: '🇧🇧',
        emergency: 'null',
        police: '211',
        ambulance: '511',
        fire: '311',
        group: 'Caribbean, North America',
        calling_codes: '+1 246',
    },
    {
        country_code: 'BY',
        country_name: 'Belarus',
        country_icon: '🇧🇾',
        emergency: 'null',
        police: '102',
        ambulance: '103',
        fire: '101',
        group: 'null',
        calling_codes: '375',
    },
    {
        country_code: 'BE',
        country_name: 'Belgium',
        country_icon: '🇧🇪',
        emergency: '112',
        police: '101',
        ambulance: '100',
        fire: '100',
        group: 'EU, Europe',
        calling_codes: '32',
    },
    {
        country_code: 'BZ',
        country_name: 'Belize',
        country_icon: '🇧🇿',
        emergency: '911',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'North America',
        calling_codes: '501',
    },
    {
        country_code: 'BJ',
        country_name: 'Benin',
        country_icon: '🇧🇯',
        emergency: 'null',
        police: '117',
        ambulance: '112',
        fire: '118',
        group: 'Africa',
        calling_codes: '229',
    },
    {
        country_code: 'BM',
        country_name: 'Bermuda',
        country_icon: '🇧🇲',
        emergency: '911',
        police: '911',
        ambulance: '911',
        fire: '911',
        group: 'British, North America',
        calling_codes: '+1 441',
    },
    {
        country_code: 'BT',
        country_name: 'Bhutan',
        country_icon: '🇧🇹',
        emergency: 'null',
        police: '113',
        ambulance: '112',
        fire: '110',
        group: 'Asia',
        calling_codes: '975',
    },
    {
        country_code: 'BO',
        country_name: 'Bolivia',
        country_icon: '🇧🇴',
        emergency: 'null',
        police: '110',
        ambulance: '118',
        fire: '119',
        group: 'South America',
        calling_codes: '591',
    },
    {
        country_code: 'BA',
        country_name: 'Bosnia and Herzegovina',
        country_icon: '🇧🇦',
        emergency: 'null',
        police: '122',
        ambulance: '124',
        fire: '123',
        group: 'Europe',
        calling_codes: '387',
    },
    {
        country_code: 'BW',
        country_name: 'Botswana',
        country_icon: '🇧🇼',
        emergency: '997 or 911',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'Africa',
        calling_codes: '267',
    },
    {
        country_code: 'BR',
        country_name: 'Brazil',
        country_icon: '🇧🇷',
        emergency: 'null',
        police: '190',
        ambulance: '192',
        fire: '193',
        group: 'South America',
        calling_codes: '55',
    },
    {
        country_code: 'IO',
        country_name: 'British Indian Ocean Territory',
        country_icon: '🇮🇴',
        emergency: 'null',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'British',
        calling_codes: '246',
    },
    {
        country_code: 'VG',
        country_name: 'Virgin Islands, British',
        country_icon: '🇻🇬',
        emergency: '999 or 911',
        police: 'null',
        ambulance: '999',
        fire: '999',
        group: 'British, Caribbean',
        calling_codes: '+ 1 284',
    },
    {
        country_code: 'BN',
        country_name: 'Brunei Darussalam',
        country_icon: '🇧🇳',
        emergency: 'null',
        police: '993',
        ambulance: '991',
        fire: '995',
        group: 'Asia',
        calling_codes: '673',
    },
    {
        country_code: 'BG',
        country_name: 'Bulgaria',
        country_icon: '🇧🇬',
        emergency: '112',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'EU, Europe',
        calling_codes: '359',
    },
    {
        country_code: 'BF',
        country_name: 'Burkina Faso',
        country_icon: '🇧🇫',
        emergency: 'null',
        police: '17',
        ambulance: '112',
        fire: '18',
        group: 'Africa',
        calling_codes: '226',
    },
    {
        country_code: 'BI',
        country_name: 'Burundi',
        country_icon: '🇧🇮',
        emergency: 'null',
        police: '117',
        ambulance: '112',
        fire: '118',
        group: 'Africa',
        calling_codes: '257',
    },
    {
        country_code: 'KH',
        country_name: 'Cambodia',
        country_icon: '🇰🇭',
        emergency: 'null',
        police: '117',
        ambulance: '119',
        fire: '118',
        group: 'Asia',
        calling_codes: '855',
    },
    {
        country_code: 'CM',
        country_name: 'Cameroon',
        country_icon: '🇨🇲',
        emergency: 'null',
        police: '17',
        ambulance: 'null',
        fire: '18',
        group: 'Africa',
        calling_codes: '237',
    },
    {
        country_code: 'CA',
        country_name: 'Canada',
        country_icon: '🇨🇦',
        emergency: '911',
        police: '911',
        ambulance: '911',
        fire: '911',
        group: 'North America',
        calling_codes: '1',
    },
    {
        country_code: 'CV',
        country_name: 'Cape Verde',
        country_icon: '🇨🇻',
        emergency: 'null',
        police: '132',
        ambulance: '130',
        fire: '131',
        group: 'Africa',
        calling_codes: '238',
    },
    {
        country_code: 'KY',
        country_name: 'Cayman Islands',
        country_icon: '🇰🇾',
        emergency: '911',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'British, Caribbean, North America',
        calling_codes: '+1 345',
    },
    {
        country_code: 'CF',
        country_name: 'Central African Republic',
        country_icon: '🇨🇫',
        emergency: 'null',
        police: '117',
        ambulance: '1220',
        fire: '118',
        group: 'Africa',
        calling_codes: '236',
    },
    {
        country_code: 'TD',
        country_name: 'Chad',
        country_icon: '🇹🇩',
        emergency: 'null',
        police: '17',
        ambulance: '2251 - 4242',
        fire: '18',
        group: 'Africa',
        calling_codes: '235',
    },
    {
        country_code: 'CL',
        country_name: 'Chile',
        country_icon: '🇨🇱',
        emergency: 'null',
        police: '133',
        ambulance: '131',
        fire: '132',
        group: 'South America',
        calling_codes: '56',
    },
    {
        country_code: 'CN',
        country_name: 'China',
        country_icon: '🇨🇳',
        emergency: 'null',
        police: '110',
        ambulance: '120',
        fire: '119',
        group: 'Asia',
        calling_codes: '86',
    },
    {
        country_code: 'CX',
        country_name: 'Christmas Island',
        country_icon: '🇨🇽',
        emergency: 'null',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'Asia',
        calling_codes: '+61 891',
    },
    {
        country_code: 'CC',
        country_name: 'Cocos (Keeling) Islands',
        country_icon: '🇨🇨',
        emergency: 'null',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'Asia',
        calling_codes: '+61 891',
    },
    {
        country_code: 'CO',
        country_name: 'Colombia',
        country_icon: '🇨🇴',
        emergency: '112 or 123',
        police: '156',
        ambulance: '132',
        fire: '119',
        group: 'South America',
        calling_codes: '57',
    },
    {
        country_code: 'KM',
        country_name: 'Comoros',
        country_icon: '🇰🇲',
        emergency: 'null',
        police: '17',
        ambulance: '772-03 - 73',
        fire: '18',
        group: 'Africa',
        calling_codes: '269',
    },
    {
        country_code: 'CD',
        country_name: 'Congo, The Democratic Republic of the',
        country_icon: '🇨🇩',
        emergency: 'null',
        police: 'null',
        ambulance: 'null',
        fire: '118',
        group: 'Africa',
        calling_codes: '243',
    },
    {
        country_code: 'CG',
        country_name: 'Congo',
        country_icon: '🇨🇬',
        emergency: 'null',
        police: '112',
        ambulance: 'null',
        fire: '118',
        group: 'Africa',
        calling_codes: '242',
    },
    {
        country_code: 'CK',
        country_name: 'Cook Islands',
        country_icon: '🇨🇰',
        emergency: 'null',
        police: '999',
        ambulance: '998',
        fire: '996',
        group: 'Oceania',
        calling_codes: '682',
    },
    {
        country_code: 'CR',
        country_name: 'Costa Rica',
        country_icon: '🇨🇷',
        emergency: '112 or 911',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'North America',
        calling_codes: '506',
    },
    {
        country_code: 'CI',
        country_name: 'Cote D\'Ivoire',
        country_icon: '🇨🇮',
        emergency: 'null',
        police: '111',
        ambulance: '185',
        fire: '180',
        group: 'Africa',
        calling_codes: '225',
    },
    {
        country_code: 'HR',
        country_name: 'Croatia',
        country_icon: '🇭🇷',
        emergency: '112',
        police: '192',
        ambulance: '194',
        fire: '193',
        group: 'EU, Europe',
        calling_codes: '385',
    },
    {
        country_code: 'CU',
        country_name: 'Cuba',
        country_icon: '🇨🇺',
        emergency: 'null',
        police: '106',
        ambulance: '104',
        fire: '105',
        group: 'North America',
        calling_codes: '53',
    },
    {
        country_code: 'null',
        country_name: 'Curaçao / Curacao',
        country_icon: '🇨🇼',
        emergency: 'null',
        police: '911',
        ambulance: '912',
        fire: '911',
        group: 'North America',
        calling_codes: '599',
    },
    {
        country_code: 'CY',
        country_name: 'Cyprus',
        country_icon: '🇨🇾',
        emergency: '112 or 199',
        police: '112, 199',
        ambulance: '112, 199',
        fire: '112, 199',
        group: 'EU, Europe',
        calling_codes: '357',
    },
    {
        country_code: 'null',
        country_name: 'Northern Cyprus',
        country_icon: '🇨🇾',
        emergency: '112',
        police: '155',
        ambulance: '112',
        fire: '199',
        group: 'Europe',
        calling_codes: '357',
    },
    {
        country_code: 'CZ',
        country_name: 'Czech Republic',
        country_icon: '🇨🇿',
        emergency: '112',
        police: '158',
        ambulance: '155',
        fire: '150',
        group: 'EU, Europe',
        calling_codes: '420',
    },
    {
        country_code: 'DK',
        country_name: 'Denmark',
        country_icon: '🇩🇰',
        emergency: '112',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'EU, Europe',
        calling_codes: '45',
    },
    {
        country_code: 'DJ',
        country_name: 'Djibouti',
        country_icon: '🇩🇯',
        emergency: 'null',
        police: '17',
        ambulance: '351351',
        fire: '18',
        group: 'Africa',
        calling_codes: '253',
    },
    {
        country_code: 'DM',
        country_name: 'Dominica',
        country_icon: '🇩🇲',
        emergency: '999',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'North America',
        calling_codes: '+1 767',
    },
    {
        country_code: 'DO',
        country_name: 'Dominican Republic',
        country_icon: '🇩🇴',
        emergency: '112 or 911',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'North America',
        calling_codes: '+1 809 / 829 / 849',
    },
    {
        country_code: 'TL',
        country_name: 'Timor-Leste',
        country_icon: '🇹🇱',
        emergency: '112',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'Asia',
        calling_codes: '670',
    },
    {
        country_code: 'EC',
        country_name: 'Ecuador',
        country_icon: '🇪🇨',
        emergency: '911',
        police: '101',
        ambulance: '911',
        fire: '102',
        group: 'South America',
        calling_codes: '593',
    },
    {
        country_code: 'EG',
        country_name: 'Egypt',
        country_icon: '🇪🇬',
        emergency: 'null',
        police: '122',
        ambulance: '123',
        fire: '180',
        group: 'Africa',
        calling_codes: '20',
    },
    {
        country_code: 'SV',
        country_name: 'El Salvador',
        country_icon: '🇸🇻',
        emergency: '911',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'North America',
        calling_codes: '503',
    },
    {
        country_code: 'GQ',
        country_name: 'Equatorial Guinea',
        country_icon: '🇬🇶',
        emergency: 'null',
        police: '114',
        ambulance: '112',
        fire: '155',
        group: 'Africa',
        calling_codes: '240',
    },
    {
        country_code: 'ER',
        country_name: 'Eritrea',
        country_icon: '🇪🇷',
        emergency: 'null',
        police: '113',
        ambulance: '114',
        fire: '116',
        group: 'Africa',
        calling_codes: '291',
    },
    {
        country_code: 'EE',
        country_name: 'Estonia',
        country_icon: '🇪🇪',
        emergency: '112',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'EU, Europe',
        calling_codes: '372',
    },
    {
        country_code: 'null',
        country_name: 'Eswatini (Swaziland)',
        country_icon: '🇸🇿',
        emergency: 'null',
        police: '999',
        ambulance: '977',
        fire: '933',
        group: 'Africa',
        calling_codes: '268',
    },
    {
        country_code: 'ET',
        country_name: 'Ethiopia',
        country_icon: '🇪🇹',
        emergency: '911',
        police: '991',
        ambulance: '907',
        fire: '939',
        group: 'Africa',
        calling_codes: '251',
    },
    {
        country_code: 'FK',
        country_name: 'Falkland Islands (Malvinas)',
        country_icon: '🇫🇰',
        emergency: '999',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'British, South America',
        calling_codes: '500',
    },
    {
        country_code: 'FO',
        country_name: 'Faroe Islands',
        country_icon: '🇫🇴',
        emergency: '112',
        police: '#ERROR!',
        ambulance: '1870',
        fire: '#ERROR!',
        group: 'EU, Europe',
        calling_codes: '298',
    },
    {
        country_code: 'FJ',
        country_name: 'Fiji',
        country_icon: '🇫🇯',
        emergency: 'null',
        police: '911',
        ambulance: '911',
        fire: '9170',
        group: 'Oceania',
        calling_codes: '679',
    },
    {
        country_code: 'FI',
        country_name: 'Finland',
        country_icon: '🇫🇮',
        emergency: '112',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'EU, Europe',
        calling_codes: '358',
    },
    {
        country_code: 'FR',
        country_name: 'France',
        country_icon: '🇫🇷',
        emergency: '112',
        police: '17',
        ambulance: '15',
        fire: '18',
        group: 'EU, Europe',
        calling_codes: '33',
    },
    {
        country_code: 'GF',
        country_name: 'French Guiana',
        country_icon: '🇬🇫',
        emergency: '112',
        police: '17',
        ambulance: '15',
        fire: '18',
        group: 'French, South America',
        calling_codes: '594',
    },
    {
        country_code: 'PF',
        country_name: 'French Polynesia',
        country_icon: '🇵🇫',
        emergency: '112',
        police: '17',
        ambulance: '15',
        fire: '18',
        group: 'French, Oceania',
        calling_codes: '689',
    },
    {
        country_code: 'GA',
        country_name: 'Gabon',
        country_icon: '🇬🇦',
        emergency: 'null',
        police: '1730',
        ambulance: '1300',
        fire: '18',
        group: 'Africa',
        calling_codes: '241',
    },
    {
        country_code: 'GM',
        country_name: 'Gambia',
        country_icon: '🇬🇲',
        emergency: 'null',
        police: '117 or 112',
        ambulance: '116',
        fire: '118',
        group: 'Africa',
        calling_codes: '220',
    },
    {
        country_code: 'GE',
        country_name: 'Georgia',
        country_icon: '🇬🇪',
        emergency: '112',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'Asia, Europe',
        calling_codes: '995',
    },
    {
        country_code: 'DE',
        country_name: 'Germany',
        country_icon: '🇩🇪',
        emergency: '112',
        police: '110',
        ambulance: 'null',
        fire: 'null',
        group: 'EU, Europe',
        calling_codes: '49',
    },
    {
        country_code: 'GH',
        country_name: 'Ghana',
        country_icon: '🇬🇭',
        emergency: '999',
        police: '191',
        ambulance: '193',
        fire: '192',
        group: 'Africa',
        calling_codes: '233',
    },
    {
        country_code: 'GI',
        country_name: 'Gibraltar',
        country_icon: '🇬🇮',
        emergency: '199 or 112 or 999',
        police: '199, 112, 999',
        ambulance: '199, 112, 999',
        fire: '199, 112, 999',
        group: 'British, Europe',
        calling_codes: '350',
    },
    {
        country_code: 'GR',
        country_name: 'Greece',
        country_icon: '🇬🇷',
        emergency: '112',
        police: '100',
        ambulance: '166',
        fire: '199',
        group: 'EU, Europe',
        calling_codes: '30',
    },
    {
        country_code: 'GL',
        country_name: 'Greenland',
        country_icon: '🇬🇱',
        emergency: '112 mobiles only',
        police: '112 mobiles only',
        ambulance: '112 mobiles only',
        fire: '112 mobiles only',
        group: 'EU, Europe',
        calling_codes: '299',
    },
    {
        country_code: 'GD',
        country_name: 'Grenada',
        country_icon: '🇬🇩',
        emergency: '911',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'North America',
        calling_codes: '+1 473',
    },
    {
        country_code: 'GP',
        country_name: 'Guadeloupe',
        country_icon: '🇬🇵',
        emergency: 'null',
        police: '17',
        ambulance: '15',
        fire: '18',
        group: 'French, Americas, North America',
        calling_codes: '590',
    },
    {
        country_code: 'GU',
        country_name: 'Guam',
        country_icon: '🇬🇺',
        emergency: '911',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'Oceania',
        calling_codes: '+1 671',
    },
    {
        country_code: 'GT',
        country_name: 'Guatemala',
        country_icon: '🇬🇹',
        emergency: 'null',
        police: '110, 120',
        ambulance: '122, 123 or 1554',
        fire: '122, 123 or 1554',
        group: 'North America',
        calling_codes: '502',
    },
    {
        country_code: 'GN',
        country_name: 'Guinea',
        country_icon: '🇬🇳',
        emergency: 'null',
        police: '122',
        ambulance: '442-020',
        fire: '1717',
        group: 'Africa',
        calling_codes: '224',
    },
    {
        country_code: 'GW',
        country_name: 'Guinea-Bissau',
        country_icon: '🇬🇼',
        emergency: '112',
        police: '112 or 117',
        ambulance: '112 or 119',
        fire: '112 or 118',
        group: 'Africa',
        calling_codes: '245',
    },
    {
        country_code: 'GY',
        country_name: 'Guyana',
        country_icon: '🇬🇾',
        emergency: '999',
        police: '911',
        ambulance: '913',
        fire: '912',
        group: 'South America',
        calling_codes: '592',
    },
    {
        country_code: 'HT',
        country_name: 'Haiti',
        country_icon: '🇭🇹',
        emergency: '118',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'North America',
        calling_codes: '509',
    },
    {
        country_code: 'HN',
        country_name: 'Honduras',
        country_icon: '🇭🇳',
        emergency: '911',
        police: '911',
        ambulance: '195',
        fire: '198',
        group: 'North America',
        calling_codes: '504',
    },
    {
        country_code: 'HK',
        country_name: 'Hong Kong',
        country_icon: '🇭🇰',
        emergency: '999 on landlines 112 on mobiles',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'Asia',
        calling_codes: '852',
    },
    {
        country_code: 'HU',
        country_name: 'Hungary',
        country_icon: '🇭🇺',
        emergency: '112',
        police: '107',
        ambulance: '104',
        fire: '105',
        group: 'EU, Europe',
        calling_codes: '36',
    },
    {
        country_code: 'IS',
        country_name: 'Iceland',
        country_icon: '🇮🇸',
        emergency: '112',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'Europe',
        calling_codes: '354',
    },
    {
        country_code: 'IN',
        country_name: 'India',
        country_icon: '🇮🇳',
        emergency: '112',
        police: '112, 100',
        ambulance: '112, 108',
        fire: '112.101',
        group: 'Asia',
        calling_codes: '91',
    },
    {
        country_code: 'ID',
        country_name: 'Indonesia',
        country_icon: '🇮🇩',
        emergency: '112',
        police: '112, 110',
        ambulance: '112, 118 or 119',
        fire: '112, 113',
        group: 'Asia',
        calling_codes: '62',
    },
    {
        country_code: 'IR',
        country_name: 'Iran, Islamic Republic Of',
        country_icon: '🇮🇷',
        emergency: '112 on mobiles',
        police: '110',
        ambulance: '115',
        fire: '125',
        group: 'Asia',
        calling_codes: '98',
    },
    {
        country_code: 'IQ',
        country_name: 'Iraq',
        country_icon: '🇮🇶',
        emergency: '122',
        police: '104',
        ambulance: 'null',
        fire: '115',
        group: 'Asia',
        calling_codes: '964',
    },
    {
        country_code: 'IE',
        country_name: 'Ireland',
        country_icon: '🇮🇪',
        emergency: '112 or 999',
        police: '112 or 999',
        ambulance: '112 or 999',
        fire: '112 or 999',
        group: 'EU, Europe',
        calling_codes: '353',
    },
    {
        country_code: 'IL',
        country_name: 'Israel',
        country_icon: '🇮🇱',
        emergency: '112 on mobiles',
        police: '100',
        ambulance: '101',
        fire: '102',
        group: 'Asia',
        calling_codes: '972',
    },
    {
        country_code: 'IT',
        country_name: 'Italy',
        country_icon: '🇮🇹',
        emergency: '112',
        police: '113',
        ambulance: '118',
        fire: '115',
        group: 'EU, Europe',
        calling_codes: '39',
    },
    {
        country_code: 'JM',
        country_name: 'Jamaica',
        country_icon: '🇯🇲',
        emergency: 'null',
        police: '119',
        ambulance: '110',
        fire: '110',
        group: 'Caribbean, North America',
        calling_codes: '+1 876',
    },
    {
        country_code: 'JP',
        country_name: 'Japan',
        country_icon: '🇯🇵',
        emergency: 'null',
        police: '110',
        ambulance: '119',
        fire: '119',
        group: 'Asia',
        calling_codes: '81',
    },
    {
        country_code: 'JO',
        country_name: 'Jordan',
        country_icon: '🇯🇴',
        emergency: '911',
        police: '911',
        ambulance: '911',
        fire: '911',
        group: 'Asia',
        calling_codes: '962',
    },
    {
        country_code: 'KZ',
        country_name: 'Kazakhstan',
        country_icon: '🇰🇿',
        emergency: '112',
        police: '102, 02',
        ambulance: '103, 03',
        fire: '101, 01',
        group: 'Asia',
        calling_codes: '+7-6xx +7-7xx',
    },
    {
        country_code: 'KE',
        country_name: 'Kenya',
        country_icon: '🇰🇪',
        emergency: '999, 999 or 911',
        police: '112, 999 or 911',
        ambulance: '999, 999 or 911',
        fire: '999, 999 or 911',
        group: 'Africa',
        calling_codes: '254',
    },
    {
        country_code: 'KI',
        country_name: 'Kiribati',
        country_icon: '🇰🇮',
        emergency: 'null',
        police: '992',
        ambulance: '994',
        fire: '993',
        group: 'Oceania',
        calling_codes: '686',
    },
    {
        country_code: 'KP',
        country_name: 'Korea, Democratic People\'S Republic of',
        country_icon: '🇰🇵',
        emergency: '112 or 119',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'Asia',
        calling_codes: '850',
    },
    {
        country_code: 'KR',
        country_name: 'Korea, Republic of',
        country_icon: '🇰🇷',
        emergency: 'null',
        police: '112',
        ambulance: '119',
        fire: '119',
        group: 'Asia',
        calling_codes: '82',
    },
    {
        country_code: 'null',
        country_name: 'Kosovo',
        country_icon: '🇽🇰',
        emergency: '112',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'EU, Europe',
        calling_codes: '383',
    },
    {
        country_code: 'KW',
        country_name: 'Kuwait',
        country_icon: '🇰🇼',
        emergency: '112',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'Asia',
        calling_codes: '965',
    },
    {
        country_code: 'KG',
        country_name: 'Kyrgyzstan',
        country_icon: '🇰🇬',
        emergency: 'null',
        police: '102',
        ambulance: '103',
        fire: '101',
        group: 'Asia',
        calling_codes: '996',
    },
    {
        country_code: 'LA',
        country_name: 'Lao People\'S Democratic Republic',
        country_icon: '🇱🇦',
        emergency: 'null',
        police: '191',
        ambulance: '195',
        fire: '190',
        group: 'Asia',
        calling_codes: '856',
    },
    {
        country_code: 'LV',
        country_name: 'Latvia',
        country_icon: '🇱🇻',
        emergency: '112',
        police: '2',
        ambulance: '3',
        fire: '1',
        group: 'EU, Europe',
        calling_codes: '371',
    },
    {
        country_code: 'LB',
        country_name: 'Lebanon',
        country_icon: '🇱🇧',
        emergency: 'null',
        police: '112 or 999',
        ambulance: '140',
        fire: '175',
        group: 'Asia',
        calling_codes: '961',
    },
    {
        country_code: 'LS',
        country_name: 'Lesotho',
        country_icon: '🇱🇸',
        emergency: 'null',
        police: '123',
        ambulance: '121',
        fire: '122',
        group: 'Africa',
        calling_codes: '266',
    },
    {
        country_code: 'LR',
        country_name: 'Liberia',
        country_icon: '🇱🇷',
        emergency: '911',
        police: '911',
        ambulance: '911',
        fire: '911',
        group: 'Africa',
        calling_codes: '231',
    },
    {
        country_code: 'LY',
        country_name: 'Libyan Arab Jamahiriya',
        country_icon: '🇱🇾',
        emergency: '1515',
        police: 'null',
        ambulance: 'null',
        fire: '193',
        group: 'Africa',
        calling_codes: '218',
    },
    {
        country_code: 'LI',
        country_name: 'Liechtenstein',
        country_icon: '🇱🇮',
        emergency: '112',
        police: '117',
        ambulance: '144',
        fire: '118',
        group: 'Europe',
        calling_codes: '423',
    },
    {
        country_code: 'LT',
        country_name: 'Lithuania',
        country_icon: '🇱🇹',
        emergency: '112',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'EU, Europe',
        calling_codes: '370',
    },
    {
        country_code: 'LU',
        country_name: 'Luxembourg',
        country_icon: '🇱🇺',
        emergency: '112',
        police: '113',
        ambulance: 'null',
        fire: 'null',
        group: 'EU, Europe',
        calling_codes: '352',
    },
    {
        country_code: 'MO',
        country_name: 'Macao',
        country_icon: '🇲🇴',
        emergency: '999, 110 or 112 on mobiles',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'Asia',
        calling_codes: '853',
    },
    {
        country_code: 'MG',
        country_name: 'Madagascar',
        country_icon: '🇲🇬',
        emergency: 'null',
        police: '117',
        ambulance: '124',
        fire: '118',
        group: 'Africa',
        calling_codes: '261',
    },
    {
        country_code: 'MW',
        country_name: 'Malawi',
        country_icon: '🇲🇼',
        emergency: 'null',
        police: '997 or 990',
        ambulance: '998',
        fire: '999',
        group: 'Africa',
        calling_codes: '265',
    },
    {
        country_code: 'MY',
        country_name: 'Malaysia',
        country_icon: '🇲🇾',
        emergency: '112 or 999',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'Asia',
        calling_codes: '60',
    },
    {
        country_code: 'MV',
        country_name: 'Maldives',
        country_icon: '🇲🇻',
        emergency: '102',
        police: '119',
        ambulance: '102',
        fire: '118',
        group: 'Asia',
        calling_codes: '960',
    },
    {
        country_code: 'ML',
        country_name: 'Mali',
        country_icon: '🇲🇱',
        emergency: 'null',
        police: '17',
        ambulance: '15, 112',
        fire: '18, 112',
        group: 'Africa',
        calling_codes: '223',
    },
    {
        country_code: 'MT',
        country_name: 'Malta',
        country_icon: '🇲🇹',
        emergency: '112',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'EU, Europe',
        calling_codes: '356',
    },
    {
        country_code: 'MH',
        country_name: 'Marshall Islands',
        country_icon: '🇲🇭',
        emergency: '911',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'COFA, Oceania',
        calling_codes: '692',
    },
    {
        country_code: 'MQ',
        country_name: 'Martinique',
        country_icon: '🇲🇶',
        emergency: 'null',
        police: '17',
        ambulance: '15',
        fire: '18',
        group: 'French, Americas, North America',
        calling_codes: '596',
    },
    {
        country_code: 'MR',
        country_name: 'Mauritania',
        country_icon: '🇲🇷',
        emergency: 'null',
        police: '117',
        ambulance: '101',
        fire: '118',
        group: 'Africa',
        calling_codes: '222',
    },
    {
        country_code: 'MU',
        country_name: 'Mauritius',
        country_icon: '🇲🇺',
        emergency: '999',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'Africa',
        calling_codes: '230',
    },
    {
        country_code: 'YT',
        country_name: 'Mayotte',
        country_icon: '🇾🇹',
        emergency: 'null',
        police: '17',
        ambulance: '15',
        fire: '18',
        group: 'French, Africa',
        calling_codes: '262',
    },
    {
        country_code: 'MX',
        country_name: 'Mexico',
        country_icon: '🇲🇽',
        emergency: '911 or 066',
        police: '66',
        ambulance: '65',
        fire: '68',
        group: 'North America',
        calling_codes: '52',
    },
    {
        country_code: 'FM',
        country_name: 'Micronesia, Federated States of',
        country_icon: '🇫🇲',
        emergency: '911',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'COFA, Oceania',
        calling_codes: '691',
    },
    {
        country_code: 'MD',
        country_name: 'Moldova, Republic of',
        country_icon: '🇲🇩',
        emergency: '112',
        police: '122',
        ambulance: '124',
        fire: '123',
        group: 'Europe',
        calling_codes: '373',
    },
    {
        country_code: 'MC',
        country_name: 'Monaco',
        country_icon: '🇲🇨',
        emergency: '112',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'Europe',
        calling_codes: '377',
    },
    {
        country_code: 'MN',
        country_name: 'Mongolia',
        country_icon: '🇲🇳',
        emergency: '100',
        police: '102',
        ambulance: '103',
        fire: '101',
        group: 'Asia',
        calling_codes: '976',
    },
    {
        country_code: 'ME',
        country_name: 'Montenegro',
        country_icon: '🇲🇪',
        emergency: '112',
        police: '102',
        ambulance: '124',
        fire: '123',
        group: 'EU, Europe',
        calling_codes: '382',
    },
    {
        country_code: 'MS',
        country_name: 'Montserrat',
        country_icon: '🇲🇸',
        emergency: 'null',
        police: '999',
        ambulance: '911',
        fire: '911',
        group: 'British, Caribbean',
        calling_codes: '+1 664',
    },
    {
        country_code: 'MA',
        country_name: 'Morocco',
        country_icon: '🇲🇦',
        emergency: '112 on mobiles',
        police: '19',
        ambulance: '15',
        fire: '15',
        group: 'Africa',
        calling_codes: '212',
    },
    {
        country_code: 'MZ',
        country_name: 'Mozambique',
        country_icon: '🇲🇿',
        emergency: 'null',
        police: '119',
        ambulance: '117',
        fire: '198',
        group: 'Africa',
        calling_codes: '258',
    },
    {
        country_code: 'MM',
        country_name: 'Myanmar',
        country_icon: '🇲🇲',
        emergency: '999',
        police: '199',
        ambulance: '192',
        fire: '191',
        group: 'Asia',
        calling_codes: '95',
    },
    {
        country_code: 'NA',
        country_name: 'Namibia',
        country_icon: '🇳🇦',
        emergency: '112',
        police: '10 111',
        ambulance: 'null',
        fire: 'null',
        group: 'Africa',
        calling_codes: '264',
    },
    {
        country_code: 'NR',
        country_name: 'Nauru',
        country_icon: '🇳🇷',
        emergency: 'null',
        police: '110',
        ambulance: '111',
        fire: '112',
        group: 'Oceania',
        calling_codes: '674',
    },
    {
        country_code: 'NP',
        country_name: 'Nepal',
        country_icon: '🇳🇵',
        emergency: '112 on mobiles',
        police: '100 or 103',
        ambulance: '102',
        fire: '101',
        group: 'Asia',
        calling_codes: '977',
    },
    {
        country_code: 'NL',
        country_name: 'Netherlands',
        country_icon: '🇳🇱',
        emergency: '112',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'EU, Europe',
        calling_codes: '31',
    },
    {
        country_code: 'NC',
        country_name: 'New Caledonia',
        country_icon: '🇳🇨',
        emergency: '112',
        police: '17',
        ambulance: '15',
        fire: '18',
        group: 'Oceania',
        calling_codes: '687',
    },
    {
        country_code: 'NZ',
        country_name: 'New Zealand',
        country_icon: '🇳🇿',
        emergency: '111',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'Oceania',
        calling_codes: '64',
    },
    {
        country_code: 'NI',
        country_name: 'Nicaragua',
        country_icon: '🇳🇮',
        emergency: '118',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'North America',
        calling_codes: '505',
    },
    {
        country_code: 'NE',
        country_name: 'Niger',
        country_icon: '🇳🇪',
        emergency: 'null',
        police: '17',
        ambulance: '15',
        fire: '18',
        group: 'Africa',
        calling_codes: '227',
    },
    {
        country_code: 'NG',
        country_name: 'Nigeria',
        country_icon: '🇳🇬',
        emergency: '112',
        police: '112',
        ambulance: '112',
        fire: '112',
        group: 'Africa',
        calling_codes: '234',
    },
    {
        country_code: 'NU',
        country_name: 'Niue',
        country_icon: '🇳🇺',
        emergency: '999',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'British, Oceania',
        calling_codes: '683',
    },
    {
        country_code: 'NF',
        country_name: 'Norfolk Island',
        country_icon: '🇳🇫',
        emergency: '999',
        police: '977',
        ambulance: '911',
        fire: '955',
        group: 'Australian, Oceania',
        calling_codes: '672',
    },
    {
        country_code: 'MK',
        country_name: 'North Macedonia',
        country_icon: '🇲🇰',
        emergency: '112',
        police: '194',
        ambulance: '192',
        fire: '193',
        group: 'Europe',
        calling_codes: '389',
    },
    {
        country_code: 'MP',
        country_name: 'Northern Mariana Islands',
        country_icon: '🇲🇵',
        emergency: '911',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'USA, Oceania',
        calling_codes: '+1 670',
    },
    {
        country_code: 'NO',
        country_name: 'Norway',
        country_icon: '🇳🇴',
        emergency: 'null',
        police: '112',
        ambulance: '113',
        fire: '110',
        group: 'Europe',
        calling_codes: '47',
    },
    {
        country_code: 'OM',
        country_name: 'Oman',
        country_icon: '🇴🇲',
        emergency: '999',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'Asia',
        calling_codes: '968',
    },
    {
        country_code: 'PK',
        country_name: 'Pakistan',
        country_icon: '🇵🇰',
        emergency: '15, 1122 landlines 112 mobiles',
        police: '15',
        ambulance: '115',
        fire: '16',
        group: 'Asia',
        calling_codes: '92',
    },
    {
        country_code: 'PW',
        country_name: 'Palau',
        country_icon: '🇵🇼',
        emergency: '911',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'COFA, Oceania',
        calling_codes: '680',
    },
    {
        country_code: 'PS',
        country_name: 'Palestinian Territory, Occupied',
        country_icon: '🇵🇸',
        emergency: 'null',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'null',
        calling_codes: '92',
    },
    {
        country_code: 'PA',
        country_name: 'Panama',
        country_icon: '🇵🇦',
        emergency: '911',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'North America',
        calling_codes: '507',
    },
    {
        country_code: 'PG',
        country_name: 'Papua New Guinea',
        country_icon: '🇵🇬',
        emergency: '111',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'Oceania',
        calling_codes: '675',
    },
    {
        country_code: 'PY',
        country_name: 'Paraguay',
        country_icon: '🇵🇾',
        emergency: '911',
        police: '912',
        ambulance: '141',
        fire: '132',
        group: 'South America',
        calling_codes: '595',
    },
    {
        country_code: 'PE',
        country_name: 'Peru',
        country_icon: '🇵🇪',
        emergency: '911',
        police: '105',
        ambulance: '105',
        fire: '106',
        group: 'South America',
        calling_codes: '51',
    },
    {
        country_code: 'PH',
        country_name: 'Philippines',
        country_icon: '🇵🇭',
        emergency: '117, 112 and 911',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'Asia',
        calling_codes: '63',
    },
    {
        country_code: 'PN',
        country_name: 'Pitcairn',
        country_icon: '🇵🇳',
        emergency: 'null',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'British, Oceania',
        calling_codes: '64',
    },
    {
        country_code: 'PL',
        country_name: 'Poland',
        country_icon: '🇵🇱',
        emergency: '112',
        police: '997',
        ambulance: '999',
        fire: '998',
        group: 'EU, Europe',
        calling_codes: '48',
    },
    {
        country_code: 'PT',
        country_name: 'Portugal',
        country_icon: '🇵🇹',
        emergency: '112',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'EU, Europe',
        calling_codes: '351',
    },
    {
        country_code: 'PR',
        country_name: 'Puerto Rico',
        country_icon: '🇵🇷',
        emergency: '911',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'North America',
        calling_codes: '+1 787',
    },
    {
        country_code: 'QA',
        country_name: 'Qatar',
        country_icon: '🇶🇦',
        emergency: '999',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'Asia',
        calling_codes: '974',
    },
    {
        country_code: 'RE',
        country_name: 'Reunion',
        country_icon: '🇷🇪',
        emergency: '112',
        police: '17',
        ambulance: '15',
        fire: '18',
        group: 'French, Africa',
        calling_codes: '262',
    },
    {
        country_code: 'RO',
        country_name: 'Romania',
        country_icon: '🇷🇴',
        emergency: '112',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'EU, Europe',
        calling_codes: '40',
    },
    {
        country_code: 'RU',
        country_name: 'Russian Federation',
        country_icon: '🇷🇺',
        emergency: '112',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'Asia, Europe',
        calling_codes: '7',
    },
    {
        country_code: 'RW',
        country_name: 'Rwanda',
        country_icon: '🇷🇼',
        emergency: '112',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'Africa',
        calling_codes: '250',
    },
    {
        country_code: 'SH',
        country_name: 'Saint Helena',
        country_icon: '🇸🇭',
        emergency: 'null',
        police: '999',
        ambulance: '911',
        fire: '999',
        group: 'British, Africa',
        calling_codes: '290',
    },
    {
        country_code: 'KN',
        country_name: 'Saint Kitts and Nevis',
        country_icon: '🇰🇳',
        emergency: 'null',
        police: '911',
        ambulance: '911',
        fire: '333',
        group: 'Caribbean, North America',
        calling_codes: '+1 869',
    },
    {
        country_code: 'LC',
        country_name: 'Saint Lucia',
        country_icon: '🇱🇨',
        emergency: '911 or 999',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'North America',
        calling_codes: '+1 758',
    },
    {
        country_code: 'null',
        country_name: 'Saint Martin',
        country_icon: '🇲🇫',
        emergency: 'null',
        police: '911',
        ambulance: '912',
        fire: '910',
        group: 'Caribbean.',
        calling_codes: '33',
    },
    {
        country_code: 'PM',
        country_name: 'Saint Pierre and Miquelon',
        country_icon: '🇵🇲',
        emergency: 'null',
        police: '17',
        ambulance: '15',
        fire: '18',
        group: 'French, North America',
        calling_codes: '508',
    },
    {
        country_code: 'VC',
        country_name: 'Saint Vincent and the Grenadines',
        country_icon: '🇻🇨',
        emergency: '999 or 911',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'North America',
        calling_codes: '+1 784',
    },
    {
        country_code: 'WS',
        country_name: 'Samoa',
        country_icon: '🇼🇸',
        emergency: '999',
        police: '995',
        ambulance: '996',
        fire: '994',
        group: 'Oceania',
        calling_codes: '685',
    },
    {
        country_code: 'SM',
        country_name: 'San Marino',
        country_icon: '🇸🇲',
        emergency: 'null',
        police: '113',
        ambulance: '118',
        fire: '115',
        group: 'Europe',
        calling_codes: '378',
    },
    {
        country_code: 'ST',
        country_name: 'Sao Tome and Principe',
        country_icon: '🇸🇹',
        emergency: 'null',
        police: '222222',
        ambulance: '221221, 221222 & 221234',
        fire: '112',
        group: 'Africa',
        calling_codes: '239',
    },
    {
        country_code: 'SA',
        country_name: 'Saudi Arabia',
        country_icon: '🇸🇦',
        emergency: 'null',
        police: '999',
        ambulance: '997',
        fire: '998',
        group: 'Asia',
        calling_codes: '966',
    },
    {
        country_code: 'SN',
        country_name: 'Senegal',
        country_icon: '🇸🇳',
        emergency: 'null',
        police: '17',
        ambulance: '33 889 1515',
        fire: '18',
        group: 'Africa',
        calling_codes: '221',
    },
    {
        country_code: 'RS',
        country_name: 'Serbia',
        country_icon: '🇷🇸',
        emergency: '112',
        police: '192',
        ambulance: '194',
        fire: '193',
        group: 'Europe',
        calling_codes: '381',
    },
    {
        country_code: 'SC',
        country_name: 'Seychelles',
        country_icon: '🇸🇨',
        emergency: '112 or 999',
        police: '133',
        ambulance: '151',
        fire: 'null',
        group: 'Africa',
        calling_codes: '248',
    },
    {
        country_code: 'SL',
        country_name: 'Sierra Leone',
        country_icon: '🇸🇱',
        emergency: 'null',
        police: '999',
        ambulance: '999',
        fire: '19',
        group: 'Africa',
        calling_codes: '232',
    },
    {
        country_code: 'SG',
        country_name: 'Singapore',
        country_icon: '🇸🇬',
        emergency: '112 on foreign mobiles',
        police: '999',
        ambulance: '995',
        fire: '995',
        group: 'Asia',
        calling_codes: '65',
    },
    {
        country_code: 'SK',
        country_name: 'Slovakia',
        country_icon: '🇸🇰',
        emergency: '112',
        police: '158',
        ambulance: '155',
        fire: '150',
        group: 'EU, Europe',
        calling_codes: '421',
    },
    {
        country_code: 'SI',
        country_name: 'Slovenia',
        country_icon: '🇸🇮',
        emergency: '112',
        police: '113',
        ambulance: 'null',
        fire: 'null',
        group: 'EU, Europe',
        calling_codes: '386',
    },
    {
        country_code: 'SB',
        country_name: 'Solomon Islands',
        country_icon: '🇸🇧',
        emergency: '999',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'Africa, Oceania',
        calling_codes: '677',
    },
    {
        country_code: 'SO',
        country_name: 'Somalia',
        country_icon: '🇸🇴',
        emergency: 'null',
        police: '888',
        ambulance: '999',
        fire: '555',
        group: 'Africa',
        calling_codes: '252',
    },
    {
        country_code: 'ZA',
        country_name: 'South Africa',
        country_icon: '🇿🇦',
        emergency: '112 on mobiles',
        police: '10111',
        ambulance: '10177',
        fire: '10111',
        group: 'Africa',
        calling_codes: '27',
    },
    {
        country_code: 'GS',
        country_name: 'South Georgia and the South Sandwich Islands',
        country_icon: '🇬🇸',
        emergency: '999',
        police: '999',
        ambulance: '999',
        fire: '999',
        group: 'British, Antartic',
        calling_codes: '500',
    },
    {
        country_code: 'null',
        country_name: 'South Sudan',
        country_icon: '🇸🇸',
        emergency: '999',
        police: '999',
        ambulance: '999',
        fire: '999',
        group: 'Africa',
        calling_codes: '211',
    },
    {
        country_code: 'ES',
        country_name: 'Spain',
        country_icon: '🇪🇸',
        emergency: '112',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'EU, Europe',
        calling_codes: '34',
    },
    {
        country_code: 'LK',
        country_name: 'Sri Lanka',
        country_icon: '🇱🇰',
        emergency: 'null',
        police: '119, 118',
        ambulance: '110',
        fire: '111',
        group: 'Asia',
        calling_codes: '94',
    },
    {
        country_code: 'SD',
        country_name: 'Sudan',
        country_icon: '🇸🇩',
        emergency: '999',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'Africa',
        calling_codes: '249',
    },
    {
        country_code: 'SR',
        country_name: 'Suriname',
        country_icon: '🇸🇷',
        emergency: '115',
        police: '115',
        ambulance: '115, 113',
        fire: '115, 110',
        group: 'South America',
        calling_codes: '597',
    },
    {
        country_code: 'SE',
        country_name: 'Sweden',
        country_icon: '🇸🇪',
        emergency: '112',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'EU, Europe',
        calling_codes: '46',
    },
    {
        country_code: 'CH',
        country_name: 'Switzerland',
        country_icon: '🇨🇭',
        emergency: '112',
        police: '117',
        ambulance: '144',
        fire: '118',
        group: 'Europe',
        calling_codes: '41',
    },
    {
        country_code: 'SY',
        country_name: 'Syrian Arab Republic',
        country_icon: '🇸🇾',
        emergency: 'null',
        police: '112',
        ambulance: '110',
        fire: '113',
        group: 'Asia',
        calling_codes: '963',
    },
    {
        country_code: 'TW',
        country_name: 'Taiwan, Province of China',
        country_icon: '🇹🇼',
        emergency: '112 on mobiles',
        police: '110',
        ambulance: '119',
        fire: '119',
        group: 'Asia',
        calling_codes: '886',
    },
    {
        country_code: 'TJ',
        country_name: 'Tajikistan',
        country_icon: '🇹🇯',
        emergency: '112 on mobiles',
        police: '102',
        ambulance: '103',
        fire: '101',
        group: 'Asia',
        calling_codes: '992',
    },
    {
        country_code: 'TZ',
        country_name: 'Tanzania, United Republic of',
        country_icon: '🇹🇿',
        emergency: '112',
        police: '112',
        ambulance: '114',
        fire: '115',
        group: 'Africa',
        calling_codes: '255',
    },
    {
        country_code: 'TH',
        country_name: 'Thailand',
        country_icon: '🇹🇭',
        emergency: '911 or 191',
        police: '191',
        ambulance: '1669',
        fire: '199',
        group: 'Asia',
        calling_codes: '66',
    },
    {
        country_code: 'TG',
        country_name: 'Togo',
        country_icon: '🇹🇬',
        emergency: 'null',
        police: '117 or 161',
        ambulance: '8200',
        fire: '118',
        group: 'Africa',
        calling_codes: '228',
    },
    {
        country_code: 'TK',
        country_name: 'Tokelau',
        country_icon: '🇹🇰',
        emergency: 'null',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'New Zealand, Oceania',
        calling_codes: '690',
    },
    {
        country_code: 'TO',
        country_name: 'Tonga',
        country_icon: '🇹🇴',
        emergency: '911',
        police: '922',
        ambulance: '933',
        fire: '999',
        group: 'Oceania',
        calling_codes: '676',
    },
    {
        country_code: 'TT',
        country_name: 'Trinidad and Tobago',
        country_icon: '🇹🇹',
        emergency: 'null',
        police: '999 or 911',
        ambulance: '811',
        fire: '990',
        group: 'Caribbean, North America',
        calling_codes: '+1 868',
    },
    {
        country_code: 'TN',
        country_name: 'Tunisia',
        country_icon: '🇹🇳',
        emergency: 'null',
        police: '197',
        ambulance: '190',
        fire: '198',
        group: 'Africa',
        calling_codes: '216',
    },
    {
        country_code: 'TR',
        country_name: 'Turkey',
        country_icon: '🇹🇷',
        emergency: '112',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'Asia',
        calling_codes: '90',
    },
    {
        country_code: 'TM',
        country_name: 'Turkmenistan',
        country_icon: '🇹🇲',
        emergency: '112',
        police: '102',
        ambulance: '103',
        fire: '101',
        group: 'Asia',
        calling_codes: '993',
    },
    {
        country_code: 'TC',
        country_name: 'Turks and Caicos Islands',
        country_icon: '🇹🇨',
        emergency: '911 or 999',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'British, Caribbean, North America',
        calling_codes: '+1 649',
    },
    {
        country_code: 'TV',
        country_name: 'Tuvalu',
        country_icon: '🇹🇻',
        emergency: 'null',
        police: '911',
        ambulance: 'null',
        fire: 'null',
        group: 'Oceania',
        calling_codes: '688',
    },
    {
        country_code: 'UG',
        country_name: 'Uganda',
        country_icon: '🇺🇬',
        emergency: '999, 112 mobiles',
        police: '999, 112',
        ambulance: '999, 112',
        fire: '999, 112',
        group: 'Africa',
        calling_codes: '256',
    },
    {
        country_code: 'UA',
        country_name: 'Ukraine',
        country_icon: '🇺🇦',
        emergency: '112',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'Europe',
        calling_codes: '380',
    },
    {
        country_code: 'AE',
        country_name: 'United Arab Emirates',
        country_icon: '🇦🇪',
        emergency: 'null',
        police: '999, 112',
        ambulance: '999, 998',
        fire: '997',
        group: 'Asia',
        calling_codes: '971',
    },
    {
        country_code: 'GB',
        country_name: 'United Kingdom',
        country_icon: '🇬🇧',
        emergency: '112 0r 999',
        police: '999 or 112',
        ambulance: '999',
        fire: '999',
        group: 'EU, Europe',
        calling_codes: '44',
    },
    {
        country_code: 'US',
        country_name: 'United States',
        country_icon: '🇺🇸',
        emergency: '911',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'North America',
        calling_codes: '1',
    },
    {
        country_code: 'UY',
        country_name: 'Uruguay',
        country_icon: '🇺🇾',
        emergency: '911',
        police: '109',
        ambulance: '105',
        fire: '104',
        group: 'South America',
        calling_codes: '598',
    },
    {
        country_code: 'UZ',
        country_name: 'Uzbekistan',
        country_icon: '🇺🇿',
        emergency: 'null',
        police: '102',
        ambulance: '103',
        fire: '101',
        group: 'Asia',
        calling_codes: '998',
    },
    {
        country_code: 'VU',
        country_name: 'Vanuatu',
        country_icon: '🇻🇺',
        emergency: '112',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'Oceania',
        calling_codes: '678',
    },
    {
        country_code: 'VA',
        country_name: 'Holy See (Vatican City State)',
        country_icon: '🇻🇦',
        emergency: 'null',
        police: '113',
        ambulance: '118',
        fire: '115',
        group: 'Europe',
        calling_codes: '+39, +379',
    },
    {
        country_code: 'VE',
        country_name: 'Venezuela',
        country_icon: '🇻🇪',
        emergency: '911, 171',
        police: '911, 171',
        ambulance: '911, 171',
        fire: '911, 171',
        group: 'South America',
        calling_codes: '58',
    },
    {
        country_code: 'VN',
        country_name: 'Vietnam',
        country_icon: '🇻🇳',
        emergency: 'null',
        police: '113',
        ambulance: '115',
        fire: '114',
        group: 'Asia',
        calling_codes: '84',
    },
    {
        country_code: 'VI',
        country_name: 'Virgin Islands, U.S.',
        country_icon: '🇻🇮',
        emergency: '911',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'US.',
        calling_codes: '+1 340',
    },
    {
        country_code: 'WF',
        country_name: 'Wallis and Futuna',
        country_icon: '🇼🇫',
        emergency: 'null',
        police: '18',
        ambulance: '15',
        fire: '17',
        group: 'French, Oceania',
        calling_codes: '681',
    },
    {
        country_code: 'EH',
        country_name: 'Western Sahara',
        country_icon: '🇪🇭',
        emergency: '150',
        police: 'null',
        ambulance: 'null',
        fire: 'null',
        group: 'Africa',
        calling_codes: '212',
    },
    {
        country_code: 'YE',
        country_name: 'Yemen',
        country_icon: '🇾🇪',
        emergency: 'null',
        police: '194',
        ambulance: '191',
        fire: '191',
        group: 'Asia',
        calling_codes: '967',
    },
    {
        country_code: 'ZM',
        country_name: 'Zambia',
        country_icon: '🇿🇲',
        emergency: '112',
        police: '999',
        ambulance: '993',
        fire: '991',
        group: 'Africa',
        calling_codes: '260',
    },
    {
        country_code: 'ZW',
        country_name: 'Zimbabwe',
        country_icon: '🇿🇼',
        emergency: '999',
        police: '995',
        ambulance: '994',
        fire: '993',
        group: 'Africa',
        calling_codes: '264',
    },
];



// https://www.rhinocarhire.com/Drive-Smart-Blog/Minimum-Driving-Age-Country.aspx
// https://www.myrentsoftware.com/minimum-age-required-hire-car-country/
// https://www.autoeurope.com/travel-tips/rental-car-age-requirements/
// https://www.kayak.co.uk/c/car-hire-guide/age-requirements/#requirements-worldwide
export const countries_driving_licenses = [
    { name: 'Afghanistan', code: 'AF' },
    { name: 'Åland Islands', code: 'AX' },
    { name: 'Albania', code: 'AL' },
    { name: 'Algeria', code: 'DZ' },
    { name: 'American Samoa', code: 'AS' },
    { name: 'Andorra', code: 'AD' },
    { name: 'Angola', code: 'AO' },
    { name: 'Anguilla', code: 'AI' },
    { name: 'Antarctica', code: 'AQ' },
    { name: 'Antigua and Barbuda', code: 'AG' },
    { name: 'Argentina', code: 'AR' },
    { name: 'Armenia', code: 'AM' },
    { name: 'Aruba', code: 'AW' },
    { name: 'Australia', code: 'AU' },
    { name: 'Austria', code: 'AT' },
    { name: 'Azerbaijan', code: 'AZ' },
    { name: 'Bahamas', code: 'BS' },
    { name: 'Bahrain', code: 'BH' },
    { name: 'Bangladesh', code: 'BD' },
    { name: 'Barbados', code: 'BB' },
    { name: 'Belarus', code: 'BY' },
    { name: 'Belgium', code: 'BE' },
    { name: 'Belize', code: 'BZ' },
    { name: 'Benin', code: 'BJ' },
    { name: 'Bermuda', code: 'BM' },
    { name: 'Bhutan', code: 'BT' },
    { name: 'Bolivia', code: 'BO' },
    { name: 'Bosnia and Herzegovina', code: 'BA' },
    { name: 'Botswana', code: 'BW' },
    { name: 'Bouvet Island', code: 'BV' },
    { name: 'Brazil', code: 'BR' },
    { name: 'British Indian Ocean Territory', code: 'IO' },
    { name: 'Brunei Darussalam', code: 'BN' },
    { name: 'Bulgaria', code: 'BG' },
    { name: 'Burkina Faso', code: 'BF' },
    { name: 'Burundi', code: 'BI' },
    { name: 'Cambodia', code: 'KH' },
    { name: 'Cameroon', code: 'CM' },
    { name: 'Canada', code: 'CA' },
    { name: 'Cape Verde', code: 'CV' },
    { name: 'Cayman Islands', code: 'KY' },
    { name: 'Central African Republic', code: 'CF' },
    { name: 'Chad', code: 'TD' },
    { name: 'Chile', code: 'CL' },
    { name: 'China', code: 'CN' },
    { name: 'Christmas Island', code: 'CX' },
    { name: 'Cocos (Keeling) Islands', code: 'CC' },
    { name: 'Colombia', code: 'CO' },
    { name: 'Comoros', code: 'KM' },
    { name: 'Congo', code: 'CG' },
    { name: 'Congo, The Democratic Republic of the', code: 'CD' },
    { name: 'Cook Islands', code: 'CK' },
    { name: 'Costa Rica', code: 'CR' },
    { name: 'Cote D\'Ivoire', code: 'CI' },
    { name: 'Croatia', code: 'HR' },
    { name: 'Cuba', code: 'CU' },
    { name: 'Cyprus', code: 'CY' },
    { name: 'Czech Republic', code: 'CZ' },
    { name: 'Denmark', code: 'DK' },
    { name: 'Djibouti', code: 'DJ' },
    { name: 'Dominica', code: 'DM' },
    { name: 'Dominican Republic', code: 'DO' },
    { name: 'Ecuador', code: 'EC' },
    { name: 'Egypt', code: 'EG' },
    { name: 'El Salvador', code: 'SV' },
    { name: 'Equatorial Guinea', code: 'GQ' },
    { name: 'Eritrea', code: 'ER' },
    { name: 'Estonia', code: 'EE' },
    { name: 'Ethiopia', code: 'ET' },
    { name: 'Falkland Islands (Malvinas)', code: 'FK' },
    { name: 'Faroe Islands', code: 'FO' },
    { name: 'Fiji', code: 'FJ' },
    { name: 'Finland', code: 'FI' },
    { name: 'France', code: 'FR' },
    { name: 'French Guiana', code: 'GF' },
    { name: 'French Polynesia', code: 'PF' },
    { name: 'French Southern Territories', code: 'TF' },
    { name: 'Gabon', code: 'GA' },
    { name: 'Gambia', code: 'GM' },
    { name: 'Georgia', code: 'GE' },
    { name: 'Germany', code: 'DE' },
    { name: 'Ghana', code: 'GH' },
    { name: 'Gibraltar', code: 'GI' },
    { name: 'Greece', code: 'GR' },
    { name: 'Greenland', code: 'GL' },
    { name: 'Grenada', code: 'GD' },
    { name: 'Guadeloupe', code: 'GP' },
    { name: 'Guam', code: 'GU' },
    { name: 'Guatemala', code: 'GT' },
    { name: 'Guernsey', code: 'GG' },
    { name: 'Guinea', code: 'GN' },
    { name: 'Guinea-Bissau', code: 'GW' },
    { name: 'Guyana', code: 'GY' },
    { name: 'Haiti', code: 'HT' },
    { name: 'Heard Island and Mcdonald Islands', code: 'HM' },
    { name: 'Holy See (Vatican City State)', code: 'VA' },
    { name: 'Honduras', code: 'HN' },
    { name: 'Hong Kong', code: 'HK' },
    { name: 'Hungary', code: 'HU' },
    { name: 'Iceland', code: 'IS' },
    { name: 'India', code: 'IN' },
    { name: 'Indonesia', code: 'ID' },
    { name: 'Iran, Islamic Republic Of', code: 'IR' },
    { name: 'Iraq', code: 'IQ' },
    { name: 'Ireland', code: 'IE' },
    { name: 'Isle of Man', code: 'IM' },
    { name: 'Israel', code: 'IL' },
    { name: 'Italy', code: 'IT' },
    { name: 'Jamaica', code: 'JM' },
    { name: 'Japan', code: 'JP' },
    { name: 'Jersey', code: 'JE' },
    { name: 'Jordan', code: 'JO' },
    { name: 'Kazakhstan', code: 'KZ' },
    { name: 'Kenya', code: 'KE' },
    { name: 'Kiribati', code: 'KI' },
    { name: 'Korea, Democratic People\'S Republic of', code: 'KP' },
    { name: 'Korea, Republic of', code: 'KR' },
    { name: 'Kuwait', code: 'KW' },
    { name: 'Kyrgyzstan', code: 'KG' },
    { name: 'Lao People\'S Democratic Republic', code: 'LA' },
    { name: 'Latvia', code: 'LV' },
    { name: 'Lebanon', code: 'LB' },
    { name: 'Lesotho', code: 'LS' },
    { name: 'Liberia', code: 'LR' },
    { name: 'Libyan Arab Jamahiriya', code: 'LY' },
    { name: 'Liechtenstein', code: 'LI' },
    { name: 'Lithuania', code: 'LT' },
    { name: 'Luxembourg', code: 'LU' },
    { name: 'Macao', code: 'MO' },
    { name: 'Madagascar', code: 'MG' },
    { name: 'Malawi', code: 'MW' },
    { name: 'Malaysia', code: 'MY' },
    { name: 'Maldives', code: 'MV' },
    { name: 'Mali', code: 'ML' },
    { name: 'Malta', code: 'MT' },
    { name: 'Marshall Islands', code: 'MH' },
    { name: 'Martinique', code: 'MQ' },
    { name: 'Mauritania', code: 'MR' },
    { name: 'Mauritius', code: 'MU' },
    { name: 'Mayotte', code: 'YT' },
    { name: 'Mexico', code: 'MX' },
    { name: 'Micronesia, Federated States of', code: 'FM' },
    { name: 'Moldova, Republic of', code: 'MD' },
    { name: 'Monaco', code: 'MC' },
    { name: 'Mongolia', code: 'MN' },
    { name: 'Montenegro', code: 'ME' },
    { name: 'Montserrat', code: 'MS' },
    { name: 'Morocco', code: 'MA' },
    { name: 'Mozambique', code: 'MZ' },
    { name: 'Myanmar', code: 'MM' },
    { name: 'Namibia', code: 'NA' },
    { name: 'Nauru', code: 'NR' },
    { name: 'Nepal', code: 'NP' },
    { name: 'Netherlands', code: 'NL' },
    { name: 'Netherlands Antilles', code: 'AN' },
    { name: 'New Caledonia', code: 'NC' },
    { name: 'New Zealand', code: 'NZ' },
    { name: 'Nicaragua', code: 'NI' },
    { name: 'Niger', code: 'NE' },
    { name: 'Nigeria', code: 'NG' },
    { name: 'Niue', code: 'NU' },
    { name: 'Norfolk Island', code: 'NF' },
    { name: 'North Macedonia', code: 'MK' },
    { name: 'Northern Mariana Islands', code: 'MP' },
    { name: 'Norway', code: 'NO' },
    { name: 'Oman', code: 'OM' },
    { name: 'Pakistan', code: 'PK' },
    { name: 'Palau', code: 'PW' },
    { name: 'Palestinian Territory, Occupied', code: 'PS' },
    { name: 'Panama', code: 'PA' },
    { name: 'Papua New Guinea', code: 'PG' },
    { name: 'Paraguay', code: 'PY' },
    { name: 'Peru', code: 'PE' },
    { name: 'Philippines', code: 'PH' },
    { name: 'Pitcairn', code: 'PN' },
    { name: 'Poland', code: 'PL' },
    { name: 'Portugal', code: 'PT' },
    { name: 'Puerto Rico', code: 'PR' },
    { name: 'Qatar', code: 'QA' },
    { name: 'Reunion', code: 'RE' },
    { name: 'Romania', code: 'RO' },
    { name: 'Russian Federation', code: 'RU' },
    { name: 'Rwanda', code: 'RW' },
    { name: 'Saint Helena', code: 'SH' },
    { name: 'Saint Kitts and Nevis', code: 'KN' },
    { name: 'Saint Lucia', code: 'LC' },
    { name: 'Saint Pierre and Miquelon', code: 'PM' },
    { name: 'Saint Vincent and the Grenadines', code: 'VC' },
    { name: 'Samoa', code: 'WS' },
    { name: 'San Marino', code: 'SM' },
    { name: 'Sao Tome and Principe', code: 'ST' },
    { name: 'Saudi Arabia', code: 'SA' },
    { name: 'Senegal', code: 'SN' },
    { name: 'Serbia', code: 'RS' },
    { name: 'Seychelles', code: 'SC' },
    { name: 'Sierra Leone', code: 'SL' },
    { name: 'Singapore', code: 'SG' },
    { name: 'Slovakia', code: 'SK' },
    { name: 'Slovenia', code: 'SI' },
    { name: 'Solomon Islands', code: 'SB' },
    { name: 'Somalia', code: 'SO' },
    { name: 'South Africa', code: 'ZA' },
    { name: 'South Georgia and the South Sandwich Islands', code: 'GS' },
    { name: 'Spain', code: 'ES' },
    { name: 'Sri Lanka', code: 'LK' },
    { name: 'Sudan', code: 'SD' },
    { name: 'Suriname', code: 'SR' },
    { name: 'Svalbard and Jan Mayen', code: 'SJ' },
    { name: 'Swaziland', code: 'SZ' },
    { name: 'Sweden', code: 'SE' },
    { name: 'Switzerland', code: 'CH' },
    { name: 'Syrian Arab Republic', code: 'SY' },
    { name: 'Taiwan, Province of China', code: 'TW' },
    { name: 'Tajikistan', code: 'TJ' },
    { name: 'Tanzania, United Republic of', code: 'TZ' },
    { name: 'Thailand', code: 'TH' },
    { name: 'Timor-Leste', code: 'TL' },
    { name: 'Togo', code: 'TG' },
    { name: 'Tokelau', code: 'TK' },
    { name: 'Tonga', code: 'TO' },
    { name: 'Trinidad and Tobago', code: 'TT' },
    { name: 'Tunisia', code: 'TN' },
    { name: 'Turkey', code: 'TR' },
    { name: 'Turkmenistan', code: 'TM' },
    { name: 'Turks and Caicos Islands', code: 'TC' },
    { name: 'Tuvalu', code: 'TV' },
    { name: 'Uganda', code: 'UG' },
    { name: 'Ukraine', code: 'UA' },
    { name: 'United Arab Emirates', code: 'AE' },
    { name: 'United Kingdom', code: 'GB' },
    { name: 'United States', code: 'US' },
    { name: 'United States Minor Outlying Islands', code: 'UM' },
    { name: 'Uruguay', code: 'UY' },
    { name: 'Uzbekistan', code: 'UZ' },
    { name: 'Vanuatu', code: 'VU' },
    { name: 'Venezuela', code: 'VE' },
    { name: 'Viet Nam', code: 'VN' },
    { name: 'Virgin Islands, British', code: 'VG' },
    { name: 'Virgin Islands, U.S.', code: 'VI' },
    { name: 'Wallis and Futuna', code: 'WF' },
    { name: 'Western Sahara', code: 'EH' },
    { name: 'Yemen', code: 'YE' },
    { name: 'Zambia', code: 'ZM' },
    { name: 'Zimbabwe', code: 'ZW' }
];

