export const shop_types: {
    label: string,
    value: string
}[] = [
        { label: 'Art Gallery', value: 'art_gallery' },
        { label: 'Automotive Showroom', value: 'automotive_showroom' },
        { label: 'Bakery', value: 'bakery' },
        { label: 'Beauty Salon', value: 'beauty_salon' },
        { label: 'Big-Box Store', value: 'big_box_store' },
        { label: 'Book Store', value: 'book_store' },
        { label: 'Brand Flagship', value: 'brand_flagship' },
        { label: 'Brand Shop', value: 'brand_shop' },
        { label: 'Brand Showroom', value: 'brand_showroom' },
        { label: 'Bread Shop', value: 'brad_shop' },
        { label: 'Cafe', value: 'cafe' },
        { label: 'Cake shop', value: 'cake_shop' },
        { label: 'Candy shop', value: 'candy_shop' },
        { label: 'Clothing Store', value: 'clothing_store' },
        { label: 'Co-operative', value: 'co_operative' },
        { label: 'Collectables', value: 'collectables' },
        { label: 'Concept Shop', value: 'concept_shop' },
        { label: 'Concession Stand', value: 'concession_stand' },
        { label: 'Convenience Store', value: 'convenience_store' },
        { label: 'Craft Shop', value: 'craft_shop' },
        { label: 'Cupcake Shop', value: 'cupcake_shop' },
        { label: 'Delicatessen', value: 'delicatessen' },
        { label: 'Department Store', value: 'Department Store' },
        { label: 'Discount Shop', value: 'discount_shop' },
        { label: 'Diy Shop', value: 'diy_shop' },
        { label: 'Dollar Shop', value: 'dollar_shop' },
        { label: 'Donut Shop', value: 'donut_shop' },
        { label: 'Dress Shop', value: 'dress_shop' },
        { label: 'Dry Cleaner', value: 'dry_cleaner' },
        { label: 'Duty-free Shop', value: 'duty_free_shop' },
        { label: 'Electronics Shop', value: 'electronics_shop' },
        { label: 'Fabric / Sewing Supplies', value: 'fabric_sewing_supplies' },
        { label: 'Farmers Market', value: 'farmers_market' },
        { label: 'Fashion Boutique', value: 'fashion_boutique' },
        { label: 'Fast Food Restaurant', value: 'fast_food_restaurant' },
        { label: 'Franchise / Chain Store', value: 'franchise_chain_store' },
        { label: 'Fruit Market', value: 'fruit_market' },
        { label: 'Furniture Store', value: 'furniture_store' },
        { label: 'Garden Center', value: 'garden_center' },
        { label: 'Gas Station', value: 'gas_station' },
        { label: 'General Store', value: 'general_store' },
        { label: 'Gift Shop', value: 'gift_shop' },
        { label: 'Hobby Shop', value: 'hobby_shop' },
        { label: 'Home Decor', value: 'home_decor' },
        { label: 'Home Improvement', value: 'home_improvement' },
        { label: 'Hypermarket', value: 'hypermarket' },
        { label: 'Imported Goods', value: 'imported_goods' },
        { label: 'Jeweler', value: 'jeweler' },
        { label: 'Junk Shop', value: 'junk_shop' },
        { label: 'Kiosk', value: 'kiosk' },
        { label: 'Kitchen Store', value: 'kitchen_store' },
        { label: 'Liquidator', value: 'liquidator' },
        { label: 'Luxury Brand Shop', value: 'luxury_brand_shop' },
        { label: 'Mattress Store', value: 'mattress_store' },
        { label: 'Mechanic / Garage', value: 'mechanic_garage' },
        { label: 'Megastore', value: 'megastore' },
        { label: 'Music Shop', value: 'music_shop' },
        { label: 'Newspaper Stand', value: 'newspaper_stand' },
        { label: 'Niche shop', value: 'niche_shop' },
        { label: 'Outdoor Shop / Outfitter', value: 'outdoor_shop_outfitter' },
        { label: 'Patisserie', value: 'patisserie' },
        { label: 'Pharmacy / Drug Store', value: 'pharmacy_drug_store' },
        { label: 'Pop-up Shop', value: 'pup_up_shop' },
        { label: 'Popular Culture', value: 'popular_culture' },
        { label: 'Reuse Cafe', value: 'reuse_cafe' },
        { label: 'Second-hand / Thrift Shop', value: 'second_hand_thrift_shop' },
        { label: 'Service Center', value: 'service_center' },
        { label: 'Software / Video Games', value: 'software_video_games' },
        { label: 'Souvenir Shop', value: 'souvenir_shop' },
        { label: 'Specialty Shop', value: 'specialty_shop' },
        { label: 'Sports Store', value: 'sports_store' },
        { label: 'Stationery Shop', value: 'stationery_shop' },
        { label: 'Street Vendors', value: 'street_vendors' },
        { label: 'Supermarket', value: 'supermarket' },
        { label: 'Surplus Shop', value: 'surplus_shop' },
        { label: 'Tailor', value: 'tailor' },
        { label: 'Takeout Restaurant', value: 'takeout_restaurant' },
        { label: 'Tattoo Shop', value: 'tattoo_shop' },
        { label: 'Ticket Vendors', value: 'ticket_vendors' },
        { label: 'Trading Shop', value: 'trading_shop' },
        { label: 'Travel Agent', value: 'travel_agent' },
        { label: 'Truck Stop', value: 'truck_stop' },
        { label: 'Variety Store', value: 'variety_store' },
        { label: 'Vegetable Market', value: 'vegetable_market' },
        { label: 'Wholesaler', value: 'wholesaler' },
    ];
